# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

jobs:
- job: build
  timeoutInMinutes: 120
  
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'org.opentestmodeling.vstep.ngt.core.parent/pom.xml'
      options: '-B'
      mavenOptions: '-Xmx4096m -Djava.net.preferIPv4Stack=true -Dhttp.keepAlive=false -Dtycho.disableP2Mirrors=true'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
    displayName: Building VSTeP/NGT Core.
