# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

jobs:
- job: build
  timeoutInMinutes: 120
  
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - script: |
      git clone -b R2_17_0 git://git.eclipse.org/gitroot/emf/org.eclipse.emf.git
      git clone -b R2_17_0 git://git.eclipse.org/gitroot/xsd/org.eclipse.xsd.git 
    displayName: Cloning EMF related repo.
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'org.eclipse.emf/pom.xml'
      mavenOptions: '-Xmx4096m -Djava.net.preferIPv4Stack=true -Dhttp.keepAlive=false'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'install'
    displayName: Building EMF.
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'org.opentestmodeling.vstep.ngt.core.parent/pom.xml'
      mavenOptions: '-Xmx4096m -Djava.net.preferIPv4Stack=true -Dhttp.keepAlive=false'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
    displayName: Building VSTeP/NGT Core.
