FROM maven:3.6-jdk-8-alpine

COPY org.opentestmodeling.vstep.ngt.core.parent/ ./

RUN MAVEN_OPTS=-Xmx2048m mvn install -DskipTests

WORKDIR org.opentestmodeling.vstep.ngt.core.web

EXPOSE 8080

CMD mvn jetty:run

