FROM maven:3.6-jdk-8-alpine

COPY org.opentestmodeling.vstep.ngt.core.parent/ ./

RUN MAVEN_OPTS=-Xmx2048m mvn -f `pwd`/pom.xml install -DskipTests

EXPOSE 8080

WORKDIR org.opentestmodeling.vstep.ngt.core.web

CMD mvn jetty:run

