FROM maven:3.6-jdk-8 as emf-build

RUN git clone -b R2_17_0 git://git.eclipse.org/gitroot/emf/org.eclipse.emf.git
RUN git clone -b R2_17_0 git://git.eclipse.org/gitroot/xsd/org.eclipse.xsd.git
WORKDIR org.eclipse.emf
RUN mvn install

FROM maven:3.6-jdk-8

COPY --from=emf-build /root/.m2/ /root/.m2/
COPY org.opentestmodeling.vstep.ngt.core.parent/ apps/

WORKDIR apps
RUN mvn clean install -DskipTest

EXPOSE 8080

WORKDIR org.opentestmodeling.vstep.ngt.core.web
RUN mvn org.apache.maven.plugins:maven-dependency-plugin:3.0.1:go-offline

CMD mvn jetty:run
